In [ ]:
import pandas as pd

In [ ]:
data = {
    "order_id" : [1,2,3,4,5,6],
    "customer" : ["Alice", "Bob", "Alice", "Dana", None, "Bob"],
    "product" : ["Book", "Book", "Pen", "Book", "Pen", "Pen"],
    "quantity" : [1, None, 3, 2, 1, None],
    "price" : ["12.99", "12.99", "1.50", "12.99", "1.50", "1.50"],
    "order_date" : ["2024-01-01", "2024-01-03", "2024/01/04", None, "2024-01-10", "2024-01-10"],
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       NaN  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       NaN   1.50  2024-01-10

In [ ]:
df.shape

(6, 6)

In [ ]:
df.head()

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       NaN  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    6 non-null      int64
 1   customer    5 non-null      object
 2   product     6 non-null      object
 3   quantity    4 non-null      float64
 4   price       6 non-null      object
 5   order_date  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 420.0+ bytes

In [ ]:
df.describe()

       order_id  quantity
count  6.000000  4.000000
mean   3.500000  1.750000
std    1.870829  0.957427
min    1.000000  1.000000
25%    2.250000  1.000000
50%    3.500000  1.500000
75%    4.750000  2.250000
max    6.000000  3.000000

In [ ]:
num_df = df.select_dtypes(include=["number"])
num_df.describe()

       order_id  quantity
count  6.000000  4.000000
mean   3.500000  1.750000
std    1.870829  0.957427
min    1.000000  1.000000
25%    2.250000  1.000000
50%    3.500000  1.500000
75%    4.750000  2.250000
max    6.000000  3.000000

In [ ]:
# Inspecting data and missing values
df.isna().sum()

order_id      0
customer      1
product       0
quantity      2
price         0
order_date    1
dtype: int64

In [ ]:
df["quantity"].isna()

0    False
1     True
2    False
3    False
4    False
5     True
Name: quantity, dtype: bool

In [ ]:
df[df["quantity"].isna()]

   order_id customer product  quantity  price  order_date
1         2      Bob    Book       NaN  12.99  2024-01-03
5         6      Bob     Pen       NaN   1.50  2024-01-10

In [ ]:
df[df["customer"].isna()]

   order_id customer product  quantity price  order_date
4         5     None     Pen       1.0  1.50  2024-01-10

In [ ]:
# handing missing values
df_drop_any = df.dropna()
df_drop_any

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
2         3    Alice     Pen       3.0   1.50  2024/01/04

In [ ]:
df_drop_subset = df.dropna(subset=["customer", "quantity"])
df_drop_subset

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None

In [ ]:
df_drop_cols = df.dropna(axis="columns", thresh = 4)
df_drop_cols

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       NaN  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       NaN   1.50  2024-01-10

In [ ]:
df_fill_zero = df.copy()
df_fill_zero["quantity"] = df_fill_zero["quantity"].fillna(0)
df_fill_zero

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       0.0  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       0.0   1.50  2024-01-10

In [ ]:
df_fill_mean = df.copy()
mean_qty = df_fill_mean["quantity"].mean()
df_fill_mean["quantity"] = df_fill_mean["quantity"].fillna(mean_qty)
df_fill_mean

   order_id customer product  quantity  price  order_date
0         1    Alice    Book      1.00  12.99  2024-01-01
1         2      Bob    Book      1.75  12.99  2024-01-03
2         3    Alice     Pen      3.00   1.50  2024/01/04
3         4     Dana    Book      2.00  12.99        None
4         5     None     Pen      1.00   1.50  2024-01-10
5         6      Bob     Pen      1.75   1.50  2024-01-10

In [ ]:
df_fill_customer = df.copy()
df_fill_customer = df_fill_customer["customer"].fillna("unknown")
df_fill_customer

0      Alice
1        Bob
2      Alice
3       Dana
4    unknown
5        Bob
Name: customer, dtype: object

In [ ]:
df_sorted = df.sort_values("order_date")
df_sorted

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       NaN  12.99  2024-01-03
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       NaN   1.50  2024-01-10
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None

In [ ]:
df_sorted["quantity_ffill"] = df_sorted["quantity"].ffill()
df_sorted

   order_id customer product  quantity  price  order_date  quantity_ffill
0         1    Alice    Book       1.0  12.99  2024-01-01             1.0
1         2      Bob    Book       NaN  12.99  2024-01-03             1.0
4         5     None     Pen       1.0   1.50  2024-01-10             1.0
5         6      Bob     Pen       NaN   1.50  2024-01-10             1.0
2         3    Alice     Pen       3.0   1.50  2024/01/04             3.0
3         4     Dana    Book       2.0  12.99        None             2.0

In [ ]:
df_sorted[["order_id", "order_date", "quantity", "quantity_ffill"]]

   order_id  order_date  quantity  quantity_ffill
0         1  2024-01-01       1.0             1.0
1         2  2024-01-03       NaN             1.0
4         5  2024-01-10       1.0             1.0
5         6  2024-01-10       NaN             1.0
2         3  2024/01/04       3.0             3.0
3         4        None       2.0             2.0

In [ ]:
df_sorted["quantity_ffill"] = df_sorted["quantity"].bfill()
df_sorted

   order_id customer product  quantity  price  order_date  quantity_ffill
0         1    Alice    Book       1.0  12.99  2024-01-01             1.0
1         2      Bob    Book       NaN  12.99  2024-01-03             1.0
4         5     None     Pen       1.0   1.50  2024-01-10             1.0
5         6      Bob     Pen       NaN   1.50  2024-01-10             3.0
2         3    Alice     Pen       3.0   1.50  2024/01/04             3.0
3         4     Dana    Book       2.0  12.99        None             2.0

In [ ]:
df_sorted[["order_id", "order_date", "quantity", "quantity_ffill"]]

   order_id  order_date  quantity  quantity_ffill
0         1  2024-01-01       1.0             1.0
1         2  2024-01-03       NaN             1.0
4         5  2024-01-10       1.0             1.0
5         6  2024-01-10       NaN             3.0
2         3  2024/01/04       3.0             3.0
3         4        None       2.0             2.0

In [ ]:
# type conversion
df.dtypes

order_id        int64
customer       object
product        object
quantity      float64
price          object
order_date     object
dtype: object

In [ ]:
df_num = df.copy()
df_num = pd.to_numeric(df_num["price"])
df_num.dtypes

dtype('float64')

In [ ]:
df_num

0    12.99
1    12.99
2     1.50
3    12.99
4     1.50
5     1.50
Name: price, dtype: float64

In [ ]:
df_bad = df.copy()
df_bad.loc[0,"price"] = "12.99 usd"
df_bad

   order_id customer product  quantity      price  order_date
0         1    Alice    Book       1.0  12.99 usd  2024-01-01
1         2      Bob    Book       NaN      12.99  2024-01-03
2         3    Alice     Pen       3.0       1.50  2024/01/04
3         4     Dana    Book       2.0      12.99        None
4         5     None     Pen       1.0       1.50  2024-01-10
5         6      Bob     Pen       NaN       1.50  2024-01-10

In [ ]:
df_bad["price_num"] = pd.to_numeric(df_bad['price'], errors = "coerce")

In [ ]:
df_bad[["price", "price_num"]]

       price  price_num
0  12.99 usd        NaN
1      12.99      12.99
2       1.50       1.50
3      12.99      12.99
4       1.50       1.50
5       1.50       1.50

In [ ]:
df_q = df.copy()
df_q["quantity"] = df_q["quantity"].fillna(0)
df_q["quantity"] = df_q["quantity"].astype("int")
df_q.dtypes

order_id       int64
customer      object
product       object
quantity       int64
price         object
order_date    object
dtype: object

In [ ]:
df

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       NaN  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       NaN   1.50  2024-01-10

In [ ]:
df_cat = df.copy()
df_cat["product"] = df_cat["product"].astype("category")

In [ ]:
df_cat.dtypes

order_id         int64
customer        object
product       category
quantity       float64
price           object
order_date      object
dtype: object

In [ ]:
df_cat["product"].cat.categories

Index(['Book', 'Pen'], dtype='object')

In [ ]:
df_time = df.copy()
df_time["order_date"]= pd.to_datetime(df_time["order_date"], errors="coerce")
df_time.dtypes

order_id               int64
customer              object
product               object
quantity             float64
price                 object
order_date    datetime64[ns]
dtype: object

In [ ]:
df_time

   order_id customer product  quantity  price order_date
0         1    Alice    Book       1.0  12.99 2024-01-01
1         2      Bob    Book       NaN  12.99 2024-01-03
2         3    Alice     Pen       3.0   1.50        NaT
3         4     Dana    Book       2.0  12.99        NaT
4         5     None     Pen       1.0   1.50 2024-01-10
5         6      Bob     Pen       NaN   1.50 2024-01-10

In [ ]:
df_time["year"]= df_time["order_date"].dt.year

In [ ]:
df_time["month"] = df_time["order_date"].dt.month

In [ ]:
df_time[["order_id","order_date", "year", "month"]]

   order_id order_date    year  month
0         1 2024-01-01  2024.0    1.0
1         2 2024-01-03  2024.0    1.0
2         3        NaT     NaN    NaN
3         4        NaT     NaN    NaN
4         5 2024-01-10  2024.0    1.0
5         6 2024-01-10  2024.0    1.0

In [ ]:
# Grouping and aggregation
df_clean = df.copy()
df_clean["quantity"] = df_clean["quantity"].fillna(0)
df_clean

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       0.0  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       0.0   1.50  2024-01-10

In [ ]:
df_clean["price"] = pd.to_numeric(df_clean["price"])
df_clean

   order_id customer product  quantity  price  order_date
0         1    Alice    Book       1.0  12.99  2024-01-01
1         2      Bob    Book       0.0  12.99  2024-01-03
2         3    Alice     Pen       3.0   1.50  2024/01/04
3         4     Dana    Book       2.0  12.99        None
4         5     None     Pen       1.0   1.50  2024-01-10
5         6      Bob     Pen       0.0   1.50  2024-01-10

In [ ]:
df_clean["order_date"] = pd.to_datetime(df_clean["order_date"], errors="coerce")
df_clean

   order_id customer product  quantity  price order_date
0         1    Alice    Book       1.0  12.99 2024-01-01
1         2      Bob    Book       0.0  12.99 2024-01-03
2         3    Alice     Pen       3.0   1.50        NaT
3         4     Dana    Book       2.0  12.99        NaT
4         5     None     Pen       1.0   1.50 2024-01-10
5         6      Bob     Pen       0.0   1.50 2024-01-10

In [ ]:
# Basic groupby
df_clean.groupby("product")["quantity"].sum()

product
Book    3.0
Pen     4.0
Name: quantity, dtype: float64

In [ ]:
df_clean.groupby("product")["quantity"].agg(["count", "sum", "mean"])

         count  sum      mean
product
Book         3  3.0  1.000000
Pen          3  4.0  1.333333

In [ ]:
df_clean["revenue"] = df_clean["quantity"] * df_clean["price"]
df_clean

   order_id customer product  quantity  price order_date  revenue
0         1    Alice    Book       1.0  12.99 2024-01-01    12.99
1         2      Bob    Book       0.0  12.99 2024-01-03     0.00
2         3    Alice     Pen       3.0   1.50        NaT     4.50
3         4     Dana    Book       2.0  12.99        NaT    25.98
4         5     None     Pen       1.0   1.50 2024-01-10     1.50
5         6      Bob     Pen       0.0   1.50 2024-01-10     0.00

In [ ]:
df_clean.groupby("customer")["revenue"].sum()

customer
Alice    17.49
Bob       0.00
Dana     25.98
Name: revenue, dtype: float64

In [ ]:
revenue_by_customer = df_clean.groupby("customer", dropna = False)["revenue"].sum().reset_index()

In [ ]:
revenue_by_customer

  customer  revenue
0    Alice    17.49
1      Bob     0.00
2     Dana    25.98
3      NaN     1.50

In [ ]:
# groupby multiple keys
df_clean0 = df_clean.groupby(["customer", "product"])["quantity"].sum()
df_clean0

customer  product
Alice     Book       1.0
          Pen        3.0
Bob       Book       0.0
          Pen        0.0
Dana      Book       2.0
Name: quantity, dtype: float64

In [ ]:
agg_table = df_clean.groupby(["product"]).agg(
    total_quantity = ("quantity", "sum"),
    avg_price = ("price", "mean"),
    num_orders = ("order_id", "count"),
    )
agg_table

         total_quantity  avg_price  num_orders
product
Book                3.0      12.99           3
Pen                 4.0       1.50           3

In [ ]:
daily_revenue = df_clean.groupby("order_date")["revenue"].sum().reset_index()
daily_revenue

  order_date  revenue
0 2024-01-01    12.99
1 2024-01-03     0.00
2 2024-01-10     1.50

In [ ]:
df_pivot = df_clean.pivot_table(
    index="customer",
    columns = "product",
    values = "quantity",
    aggfunc = "sum",
    fill_value = 0,
)
df_pivot

product   Book  Pen
customer
Alice      1.0  3.0
Bob        0.0  0.0
Dana       2.0  0.0

In [ ]:
df_long = df_pivot.reset_index().melt(
 id_vars = "customer",
 value_vars = df_pivot.columns,
 var_name = "product",
 value_name = "quantity"
)

df_long.head()

  customer product  quantity
0    Alice    Book       1.0
1      Bob    Book       0.0
2     Dana    Book       2.0
3    Alice     Pen       3.0
4      Bob     Pen       0.0

In [ ]:
import pandas as pd
import numpy as np

# 1. Create & inspect the DataFrame
data2 = {
    "city": ["NY", "LA", "NY", "SF", "LA", "NY"],
    "store_id": [1, 2, 1, 3, 2, 1],
    "sales": ["100.0", "200.5", None, "300", "250.0", "120.0"],
    "customers": [10, 20, 15, None, 22, 12],
}
stores = pd.DataFrame(data2)

print("=== 1. INSPECT ===")
print(stores)
print(stores.dtypes)
print(stores.isna().sum())

# 2. Handle missing values
stores['sales'] = pd.to_numeric(stores['sales'], errors='coerce')
sales_mean = stores['sales'].mean()  # ~194.1
stores['sales'] = stores['sales'].fillna(sales_mean)
stores = stores.dropna(subset=['customers'])  # Drop SF row

# 3. Convert types
stores['city'] = stores['city'].astype('category')
stores['store_id'] = stores['store_id'].astype('int32')

print("\n=== 2-3. CLEANED ===")
print(stores)
print(stores.dtypes)

# 4. Grouped aggregation
grouped = stores.groupby('city').agg({
    'sales': 'sum',
    'customers': 'mean'
}).round(2)

print("\n=== 4. GROUPED AGGREGATION ===")
print(grouped)

# 5. Pivot table (handles duplicate NY store 1)
pivot = stores.pivot_table(
    index='city',
    columns='store_id',
    values='sales',
    aggfunc='sum'
)

print("\n=== 5. PIVOT TABLE ===")
print(pivot)

=== 1. INSPECT ===
  city  store_id  sales  customers
0   NY         1  100.0       10.0
1   LA         2  200.5       20.0
2   NY         1   None       15.0
3   SF         3    300        NaN
4   LA         2  250.0       22.0
5   NY         1  120.0       12.0
city          object
store_id       int64
sales         object
customers    float64
dtype: object
city         0
store_id     0
sales        1
customers    1
dtype: int64

=== 2-3. CLEANED ===
  city  store_id  sales  customers
0   NY         1  100.0       10.0
1   LA         2  200.5       20.0
2   NY         1  194.1       15.0
4   LA         2  250.0       22.0
5   NY         1  120.0       12.0
city         category
store_id        int32
sales         float64
customers     float64
dtype: object

=== 4. GROUPED AGGREGATION ===
      sales  customers
city
LA    450.5      21.00
NY    414.1      12.33

=== 5. PIVOT TABLE ===
store_id      1      2
city
LA          0.0  450.5
NY        414.1    0.0

/tmp/ipykernel_306/1801249461.py:33: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = stores.groupby('city').agg({
/tmp/ipykernel_306/1801249461.py:42: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = stores.pivot_table(